"""Adiciona coluna tipo em members

Revision ID: 388614b293e7
Revises: 
Create Date: 2026-07-24 22:56:18.711243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388614b293e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
